{% set version = "1.1.2" %}


package:
  name: django-mustache
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/django-mustache/django-mustache-{{ version }}.tar.gz
  sha256: 44d29f56e0cf4a52cb12e2e97d5a45fd6f1242eb5d5ae79af4750ab83083a8b4

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - django >=1.8
    - pystache
    
test:
  requires:
    - python {{ python_min }}
  imports:
    - django_mustache
    
about:
  home: https://github.com/wq/django-mustache
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Mustache (Pystache) template engine for Django 1.8 and newer, with support for Django 
            context processors. Designed to support offline-capable web apps via progressive enhancement.'
  description:  A straightforward Mustache-powered template engine for Django, extracted from wq.db 
                and updated to support the new template backend infrastructure in Django 1.8 and newer. 
                django-mustache facilitates progressive enhancement by allowing you to share the same 
                templates between Django and an offline-capable JavaScript web app. Combined with a shared 
                URL structure, this approach ensures that each page in your site can be selectively 
                rendered on the server or on the client as needed.  
  doc_url: https://github.com/wq/django-mustache
  dev_url: https://github.com/wq/django-mustache

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
