travis:
  secure:
    BINSTAR_TOKEN: Y7yNp6Mu5bAJqEXFo0y0/IGUxDXT/I+GEd9gT4TtnyO1B8rHpG4fZ490OM+AKOCJKWcG8Y1XY9SWdT5HO8ScDzNhxAiHCi7MEiCzRcpVLYJAiCHbF7fEaqd7G/bZrvCiUP1l1dEYBedxD3kVqgTQMaABvbuHkdb/1FeYLpwTGe7DWEnITvy/SRLTviQmNK7I34bfVxrSb90WmMYqAUiPWBcJbGdLWW/2SX+UBqoydqJ9GJoyvAoGf7S4Bhjj4j6f9MfoCX92kW1mQnvjLv+kXrbp3dh21/E5kEyNfECNNQZhl3j80s+A7LWhTpI07QvCu/7pBqeKZI+6f2SBZ8pAxVrNzELPec/Hqt0nb6EbsJPY1acugcno+h+5XE6BUKMLrAhRpiZLnH5CWn6qDtv/+vwxL+rkpGyLhF5YurfslWgHNphSUAu0vTF7Qb4ec1j6yuXMfat1hhS6OSeiDfpVUuz/b/30c+pcYYVRiuA+jsvdVdgCx1B4YGB1DYto97h3CvECWH/FqicyTnfMjjvLOHcfuuZk3IOlwryBUPhEj9k+ugfcKNqf680nH3KjF9Ry9bIaFoCW1bRtCTKYA1+oV5/bKitYDpINofuphnS0lyhE4my1aqkK1nrO6NsXPXWV3QpcqZC3OzgZ4ikDCNJ/vy2fRnTR3hSBVNQXSeMf6g8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
