travis:
  secure:
    BINSTAR_TOKEN: U3blvpjnHui1irX3qiS3APnjP0Tr4nDKatblohQrO2H6xsAZrD07WANvwVulb0ovqDqTZ7wW7Yp87FGPIxaRI66yUUH1rEQFOt1Ki3txxYoZwtPagdlBMnrSQllyaTJw9ftcggoGocSnZEAW4QPun3fp4G10pABJDuL+PWSu7DT6sIvMtm2XmzKM/y8mMhNUgdXp64IXQTOxb8MmmFfeyzPzVvlqKbU44dKpRMZ8qllcbFSAOl/tvqzZ6RN6m3OqvyuZgqnPNTmKor+Z1ubvLQi0efAnk8RXjPDNb9mCRIeElCAqSHQLdxOxtZzWphuitcrLWcAdXAR2IKI+wRrPUocGf9okHqwwX/WI7CzSZmoy9mjip+LyDomwLksg7amWHZz/yifCuJrhXVQQASpNRS4mJXv5WggrU6St68qdbieIvYblOWtKiSqtLnOMZvm/TVmkfeVS0U6IGDmMW23YI9E8G/eCEXnOXMeOt02BfoPf1mN+5PpBb2/MjJxNAxKAG1uA9k9MTI7oHcE0LZRkZyJLoKCqDYvnqJewSFb5dvzQtrWLxl7L4ED7AqFYO/l+hEVahE0nBjAaRWZ+vy5qshtS/xkqZR7G7T8TasLsYkfd5+RLAy7JmfQfhTTCiRZ+3H70OLFxuU8dynLHZPWWxEpI1/IuHEXVYkjV15anwzM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
